const site = `<?xml version="1.0" encoding="utf-8"?><rss xmlns:a10="http://www.w3.org/2005/Atom" version="2.0"><channel><title>RoyalRoadL Fiction Syndication</title><link>https://royalroadl.com/fiction/syndication/11209</link><description>Latest updates of the fictions (The Legend of Randidly Ghosthound)</description><language>en-US</language><generator>RoyalRoadL</generator><item><guid isPermaLink="false">195715</guid><link>http://royalroadl.com/fiction/chapter/195715</link><title>The Legend of Randidly Ghosthound - Chapter 363</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Alright switch.” Alana’s voice sounded out, and Thea fell to her knees, almost grateful. &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;The person opposite her, a short woman with extremely powerful legs, lowered the huge shield that she used as a weapon. Her gaze scrutinized Thea carefully, absorbing every detail. But as she was turning away, all the woman said was, “You… can improve very quickly. Good luck.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Thea was too exhausted after their brief duel to respond, but her eyes locked onto the IX on the back of that woman’s leather armor. So, she was part of the 9th Squad. That made Thea feel… at least some swelling of pride, even though she had been absolutely embarrassed on every front.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;But that was common, in this exercise: of the 19 duels Thea had participated in, there was only one that could be even considered a draw. The level in Donnyton… was so fucking high, it hurt.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;The training had started with an hour of exhausting fitness exercises with weights, the 300 people moving with remarkable efficiency to make sure everyone did everything. Thea sorta ended up swept up in the momentum, and lost herself in the weight lifting. The exercises were many and varied, and pushed her body beyond what she thought was possible, earning Thea two Levels in Physical Fitness.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Then the duels began, in Alana’s words, to determine “the final groups”.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Thea really didn’t want to know what group she had ended up in. She had gained a dozen or so Skill Levels, however, and tried to focus on this, rather than her actual performance, which left her flushed with shame. If Chrysanthemum were participating…&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;But Thea knew that this was just an excuse; these people were relying on their own strength, (...)</description><pubDate>Tue, 20 Feb 2018 05:39:54 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">195714</guid><link>http://royalroadl.com/fiction/chapter/195714</link><title>The Legend of Randidly Ghosthound - Chapter 362</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;Randidly tried his best to keep is face even. “Surely… this amount of… data is unnecessary, for our purposes.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Oh, I disagree,” Mrs. Hamilton said smoothly, her smile wide. “Surely, as the founder of Donnyton… taking the time to write out some concrete advice for this many people is just par for the course? And if you are to make intelligent decisions, you need to be informed.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Trying not to let the headache force him to lose his temper, Randidly said slowly. “...I’m a warrior, that’s my job. Sure, knowing this political and economic and scientific information might be useful in the long run, but-”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Incorrect.” Mrs. Hamilton’s voice was low, and the small smile she usually wore slowly fell away, revealing a deep, implacable determination. Carefully, she folded her hands and gave Randidly a long, and searching look.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Perhaps you aren’t really playing dumb, you just haven’t… conceptualized it. You haven’t named it. The people here, Randidly, they venerate you. Most of them haven’t met you, they’ve only heard stories. Watched the people they admire watch people those people admire, admiring &lt;/span&gt;&lt;em&gt;&lt;span style="font-weight: 400"&gt;you&lt;/span&gt;&lt;/em&gt;&lt;span style="font-weight: 400"&gt;. That means something. The weight of those feelings changes things, whether you like it or not.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Leaning forward, Mrs. Hamilton said. “Look, I understand what you said earlier, you need to focus on figuring out how to… well perhaps some things are best to be left unsaid. You want to create something uniquely yours. But I think that you will find 4 hours working on this now will save you innumerable troubles down the line, and affect your research very little. You need a legacy. These letters… they will start that legacy, even if the recipients (...)</description><pubDate>Tue, 20 Feb 2018 05:36:49 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">195713</guid><link>http://royalroadl.com/fiction/chapter/195713</link><title>The Legend of Randidly Ghosthound - Chapter 361</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Hmph,” Paolo crossed his arms, his squad gathering up behind him. “As if a simple test of courage could cause I, the great leader of Squad III, to feel fear.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Hohoho… then why are so slow to agree? Any member of Squad II would gladly throw themselves in the line of danger. Your hesitation… is unbecoming. Perhaps in your age-” Kayle said, his tone teasing, his Squad too gathering up, but he was interrupted.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Choose quick. Boring.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Dinesh tried not to tremble as the huge giant Bone Wurm rumbled down at them, weaving its head back and forth. Her. Her head, Dinesh had been told. He resisted the urge to say a small prayer.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Initially, Dinesh had been secretly overjoyed that after their joint exercise in the North, against the Skeleton Knight, Paolo and Kayle invited him and the rest of the 23rd Squad to join them for a “celebration”. Very eagerly, they had agreed. It wasn’t rare to see the Numeral Squads around, but it was an usual thing for them to fraternize so openly with a Squad in the 20s. This could be a big move for them.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;And Dinesh had high hopes of making friends, learning secrets, and working to improve himself in his Squad. To his chagrin, the final thing had come true. &lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Their version of celebration was an elongated practice session designed by the Dusk Spider, Mrs. Hamilton, to draw out the entire physical potential of the exerciser. Primarily, it increased the Physical Fitness, Empower, and Herculean Strength Skills, which most of all of the Classed individuals had. Even Dinesh, who was a mage focus, as well as his Squad, had them.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;However, his mage focused squad was a long, long way of being able to keep up with workouts (...)</description><pubDate>Tue, 20 Feb 2018 05:33:27 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">195712</guid><link>http://royalroadl.com/fiction/chapter/195712</link><title>The Legend of Randidly Ghosthound - Chapter 360</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;Donny swirled the wine in his cup, staring out the window into the darkness, looking extremely thoughtful. He was in his full armor, a carefully shaped bone creation, with golden accents, giving him the look of a powerful and honorable knight. His helmet and shield were on the table, but still, with the armor, he felt that he looked profoundly capable.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Daniel snorted, slamming his papers down on the desk in front of him. “You look like a constipated idiot, you know that right?”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“I look refined and thoughtful, like the leader of the free world.” Donny said, never even flinching at Daniel’s tirade or the noise. Instead, his gaze focused studiously on the darkness outside of his window. His Stats were just high enough to pierce the veil of darkness that would have prevented most people from seeing, and he could watch the small movements of people who worked through the night.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;One big plus of the System was the increased productivity. This varied, based upon Endurance and Vitality, but for the strongest of them, sleep was only a rarely indulged treat. Still, Mrs. Hamilton had wondered on the long term psychological effect of this, so a lot of people continued to sleep, if only for the reset factor. It still did wonders with shifting your mood, if you were stuck somewhere you didn’t want to be.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“He might not come tonight.” Daniel said, sighing and returning to his paperwork.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Donny nodded slowly. “...Yea, he probably won’t.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Then why are you doing this? We should just do some real work, not this… theatrical farce.” Daniel said sourly.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Shrugging, Donny turned back to the desk and looked at the papers there. Although they hadn’t quite (...)</description><pubDate>Tue, 20 Feb 2018 05:29:18 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">194413</guid><link>http://royalroadl.com/fiction/chapter/194413</link><title>The Legend of Randidly Ghosthound - Chapter 359</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;As the Ghosthound nodded slowly to the name, Dozer folded his hands together. “Why examine her?”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;The Ghosthound glanced at the other man, then back over towards Delilah. “My… Blessings formed a connection with the four people I gave them to. That gives them… certain benefits. And it seems...the connection split off, so there is a further connection, from me to Delilah, moving through Annie.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Randidly tapped his jaw. “I was just thinking… I wonder how the Aether is filtered, whether it holds more of Annie’s meaning, when it flows through her… Also… it’s not as large as the connection to Annie, although I’m not sure whether that is due to age, or…”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Trailing off, the Ghosthound just stared at Delilah, his brow furrowed. Dozer stood, taking both of the dishes over to the sink. Then he asked, over his shoulder. “Will she be strong?”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“...Yes, without a doubt,” Randidly said, chuckling. Then he stood and went to the door. As he passed the threshold, he said. “But I think that’s more a reflection of her parents, than anything else. I’ll have to make a gift for her.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Oh! Don’t tell anyone the name.” Annie called after him into the darkness. “It’s only been a few weeks… the naming ceremony is going to be Saturday, once she looks presentable. Bring your gift then.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;*****&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Randidly couldn’t help but feel disappointed when he knocked on the door to Mrs. Hamilton’s house, in the dead of night, and she opened it almost instantly. There were two cups of tea on the table, so she had known he was coming. Taking a sip, he winced; it was still warm.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;How the fuck did she know that…?&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span (...)</description><pubDate>Wed, 14 Feb 2018 06:32:28 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">194412</guid><link>http://royalroadl.com/fiction/chapter/194412</link><title>The Legend of Randidly Ghosthound - Chapter 358</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;Annie was holding her baby to her chest when Dozer came into their small home. The walls on either side of her were decorated very differently. On her left, the walls were covered with hanging claws and fangs, the natural weapons of beasts that Dozer had crushed. There was even a long, thin scorpion stinger hanging up there, a testament to the variety of creatures that he had killed.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;On the right wall were skulls. And each skull had a small crack, a hole, that had been pierced by an arrowhead. While they had been living. The number of skulls was almost double the number of sets of claws and fangs.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Dozer took one look at the stove, where a pot was already bubbling, and said, “You knew I was back.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Simply nodding, Annie continued to poke her baby’s nose. Delilah seemed to be largely unable to feel it, and just sat there. It was amazing, the way the cartilage of the baby’s nose bent and reformed so easily under the pressure from Annie’s finger. It was still incredible to her that this thing came out of her. And she could easily tell that this little thing was a smashed up and ugly mix of the both of them.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;‘Well,’ Annie thought to herself, ‘maybe the ugly part is just Dozer’s half…’&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Stop making that face, the baby isn’t that ugly,” Dozer said simply, going to the pot and picking up the bowl she had set out for him. Annie shot an annoyed glance at his back. This was an increasingly problematic pattern emerging in his behavior; Dozer was becoming almost impossibly good at sensing her emotions, just from looking at her.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;It scared her a little. Because it made her feel exposed and out of control. But at the same time…&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;That’s why they (...)</description><pubDate>Wed, 14 Feb 2018 06:28:36 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">194410</guid><link>http://royalroadl.com/fiction/chapter/194410</link><title>The Legend of Randidly Ghosthound - Chapter 357</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;Alana felt on fire, moving and reacting, predicting and being predicted. The Ghosthound’s Style of fighting was not her own; where she relied on strength and breaking the opponent’s momentum, the Ghosthound seemed to steal the very momentum from her as she was moving.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Her spear flashed forward, aiming to inflict a strike on his shoulder, but he simply stepped forward and sideways, and his foot flashed upwards, catching her in the gut and sending her sprawling, the light about her dimming. Alana winced. That hit was like a truck, even after Child of the Sun took off a flat percentage of its force. God, how high were his stats?&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“Attention up, you lost me.”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Alana blinked, and realized that she really had; the Ghosthound was gone. The air around was quiet. Instinctively, she raised her shield above her head and brought her spear across her body, her eyes scanning for an enemy. Then the world… seemed to darken, and she spotted something out of the corner of her eye.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;She gasped, or at least tried to, as she spun around, but she found that the air was stuck in her throat. Her chest heaved, but her lungs seemed suddenly cast from stone, unable to inflate and pump oxygen into her blood. Which just made her panic, and stumble, her head abruptly pounding at the pressure in her chest.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;In front of her, standing about 10 meters away, was the Ghosthound, his eyes a brilliant emerald, seeming to pierce right through her, freezing her chest. Her eyes narrowed, and she forced the panic in her chest down. She would not break from just this.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;She could feel streams of energy flowing to her, as the rays of sunlight were bent by her Skill, twisting towards her, making her warm and glowing with (...)</description><pubDate>Wed, 14 Feb 2018 06:27:01 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">194409</guid><link>http://royalroadl.com/fiction/chapter/194409</link><title>The Legend of Randidly Ghosthound - Chapter 356</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;Alana sidestepped, letting Tykes’ huge iron ball fly past her and slam into the tree behind her.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“If you telegraph like that, even Dozer will seem like a ballerina fighting you,” Alana said as she snorted decisively and advanced towards Tykes. The boy was strong, sure, but he wasn’t strong enough for him to just rely on raw power, yet he repeatedly tried.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;As the boy’s shit eating grin didn’t change, Alana realized there was something else to this, but she didn’t change her movements. Only, her right hand tightened on her spear, while her left kept an even grip on the spear, and she began to glow a warm red color as her energy gathered into her body. Better to rely on her Skills to suppress him. It wasn’t really fair for her to use her Lvl 47 Stats to oppress a Level 35.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;There was a whistling behind her, as the iron ball ricocheted off a tree and changed direction. Out of the corner of her eye she could see that the ball was rotating rapidly, and it began to curve towards her back. Clever, but this she was already prepared for, since the moment he chose to fight with a weapon that left his hands. If he didn’t manage at least this much, he wouldn’t be much use against monsters with actual powers.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Her Child of the Sun Skill just burned that much brighter to compensate, and she could see Tykes cover his eyes: there.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Her body blurred as she rushed forward, ignoring the iron ball as it rushed towards her back. Immediately, his senses picked up on her change of pace, and he began to backpedal rapidly. With a gesture, he somehow managed to increase the speed by which the ball was moving, and the air seemed to hum behind her.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Tsk’ing to herself, Alana spun to the side and let the (...)</description><pubDate>Wed, 14 Feb 2018 06:24:01 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">194186</guid><link>http://royalroadl.com/fiction/chapter/194186</link><title>The Legend of Randidly Ghosthound - Chapter 355</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;After being rocked back and forth like a baby for about 10 minutes, Arbor had calmed down enough to let him back on his feet. Randidly brushed most of the ash off of him, and turned to Kiersty, who seemed content to just standby and watch the process. The men and women in robes behind her were just watching wide eyed, most of them aware of who he was now.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;There was… something in their eyes. Worship. Randidly’s mentality had make great strides since the arrival of the System, but this… this was something new. This was a strange form of pressure apart from responsibility that was cloying and sticky. He shifted uncomfortably, turning to Kiersty.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;“So… where did the spiders come from?” Randidly asked, his eyes scanning the nearby treetops, seeing the hundreds of thousands of tiny spiders that skittered around.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Kiersty shrugged. “...we don’t really know. One day, they just came out of Arbor, and started making this area. But he said they came from you, and they could be controlled, so we communicated with them to stay in a certain area….”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;For the first time since Randidly arrived, Kiersty frowned, seemingly confused. “...you don’t know what they are…?”&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Randidly opened his mouth, then closed it. Because he could suddenly feel Lucretia’s amusement, and made the connection. Arbor’s connection to his Soul Skill… had let a life form similar to the Weavers from inside of him come out into the world…?&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Now that Randidly knew what he was looking for, he focused his vision, feeling threads of Aether. There was a thick rope going from himself to Arbor, which flowed into the surrounding Aether. But from Arbor, there was also two smaller flows of Aether, one of which, to Randidly’s surprise, (...)</description><pubDate>Tue, 13 Feb 2018 05:58:17 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item><item><guid isPermaLink="false">194185</guid><link>http://royalroadl.com/fiction/chapter/194185</link><title>The Legend of Randidly Ghosthound - Chapter 354</title><description>&lt;p&gt;&lt;span style="font-weight: 400"&gt;Randidly wandered North from where he had landed, struck by the strange feeling that he knew this area, this farm. There was no one around, which was slightly strange, but he supposed there had been some very physical repercussions to him dislodging the giant Aether construct that had hovered above the Village, and people had noticed.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Perhaps they had evacuated somewhere…? Fleeing from the fallout zone?&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;There were the sounds of birds in the air, but no people. No talking, no work, no toil, no monsters… just birds. Chipmunks, squirrels…. Randidly’s sharpened senses picked out the sound of a deer moving through the treeline around him.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Then he arrived at it, and it all came flooding back. The small cabin that Randidly had claimed for himself all those years ago, at the thin edge of the valley where Donnyton sat. It was immaculately preserved, the small field where he had began farming still sitting there, a line of corn springing up.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Of course, the big field that Randidly had expanded to…. He looked behind him and sighed, surveying the crater. Well, hopefully it is no longer really in use, and no one will mind his landing… But &lt;/span&gt;&lt;em&gt;&lt;span style="font-weight: 400"&gt;someone &lt;/span&gt;&lt;/em&gt;&lt;span style="font-weight: 400"&gt;had to be here maintaining it…&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;...A problem for another time. Randidly turned his attention to the small path that lead away from his old area, deeper into the trees. Silently, almost against his will, he found his feet moving, carrying him deeper. Perhaps it was ironic, that this would be the first location that he would go after returning, cementing his status as someone who cared little about people, but Randidly didn’t mind so much.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style="font-weight: 400"&gt;Besides, Randidly could (...)</description><pubDate>Tue, 13 Feb 2018 05:51:02 Z</pubDate><a10:updated>1970-01-01T00:00:00Z</a10:updated></item></channel></rss>`

const express = require('express')
const axios = require('axios');
const app = express()
const port = process.env.PORT || 3000

const UpdateChaptersURL = "https://us-central1-westernnovelupdates.cloudfunctions.net/updateChapters"

app.get('*', async (req, res) =>
{
    try
    {
        let updatedChaptersResponse = await axios.post(UpdateChaptersURL, site, 
            {headers:{"Content-Type": "text/plain"}})
       
        res.send(updatedChaptersResponse)
    }
    catch(err)
    {
        res.status(500).send(err)
    }
})

app.listen(port, () =>
{
    console.log(`Feeder running at ${port}`)
})